config/routes.rb
Rails.application.routes.draw do
  
  # resources :themes
  resources :parties do
    resources :comments, only: [:show, :edit, :update, :destroy, :new]
  end

  
  resources :comments, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :users, only: [:new, :create, :destroy, :update, :show]
  resources :rsvps, only: [:new, :create, :destroy]
  resources :hosts, :controller => 'users', type: "Host"
  resources :guests, :controller => 'users', type: "Guest"
  
  get '/home' => 'users#index'
  get '/users' => 'users#new'
  get '/user/edit' => 'users#edit'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  #need to delete this logout get path later on
  post '/logout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#facebook_omniauth'
  get '/auth/google_oauth2/callback' => 'sessions#google_omniauth' 

  root "sessions#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/party.rb
class Party < ApplicationRecord
  validates_presence_of :name
  validates_presence_of :capacity  
  validates_numericality_of :capacity

  belongs_to :host, foreign_key: :user_id
  belongs_to :theme
  has_many :rsvps, dependent: :destroy
  has_many :guests, through: :rsvps, foreign_key: :user_id
  has_many :comments, dependent: :destroy
  has_many :users, through: :comments

  accepts_nested_attributes_for :theme

  scope :search,-> (name){where("name LIKE ?", "%#{name}%")}

  scope :popular_parties, -> {
    left_joins(:rsvps)
    .select("parties.*, count(rsvps.id) AS total_rsvps")
    .group("parties.id")
    .order("total_rsvps DESC")
  }

  scope :newest_party, -> {order("created_at DESC")}
  scope :oldest_party, -> {order("created_at ASC")}

  # scope :theme_search, -> (theme_name){
  #   left_joins(:themes)
  #   .select("parties.*")
  #   .where("theme.name LIKE ?", "%#{theme_name}%")
  # }

  def theme_attributes=(theme)
    self.theme = Theme.find_or_create_by(name: theme[:name])
    self.theme.update(theme)
  end

  def self.filter_by_params(input)
    if !input.empty?
      params= input.values
      byebug
      Party.send(params.first)
    else
      Party.all
    end
  end


end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_action :require_login
  skip_before_action :require_login, only: [:index]

  def index
    if params[:search]
      @params= params.permit(:search).to_h
      @parties = Party.search(params[:search])
    else
      @params = params.permit(:popular_parties, :newest_party, :oldest_party, :sort)
      #got rid of .to_h
      @parties = Party.filter_by_params(@params)
    end
  end

  def show
    @party= Party.find(params[:id])
    @rsvp = current_user_rsvp(@party)
  end

  def new
    if current_user.type == "Host"
      @party = Party.new
      @party.theme = Theme.new
    else
      flash[:alert] = "You don't have site privledges to create an event."
      redirect_to parties_path
    end
  end

  def create
    @party = Party.new(party_params)
    @party.host = current_user
    if @party.save
      redirect_to party_path(@party)
    else
      render :new
    end
  end

  def edit
    @party= Party.find(params[:id])
    return head(:forbidden) unless current_user == @party.host
  end

  def update
    @party= Party.find(params[:id])
    @party.update(party_params)
    if @party.save
      redirect_to party_path
    else
      render :edit
    end
  end

  def destroy
    party = Party.find(params[:id])
    party.destroy
    redirect_to parties_path
  end
  
  private

  def party_params
    params.require(:party).permit(:name, :capacity, :about, theme_attributes: [:name, :era])
  end

  def current_user_rsvp(party)
    current_user.rsvp_ids.each do|id|
      if id == party.rsvp_ids
        id
      end
    end
  end

end

app/helpers/parties_helper.rb
module PartiesHelper

  def rsvp_button(party)
    if party.guests.count == party.capacity
      "This party is currently at capacity. Check back later to see if any space opens up."
    elsif current_user.type == "Guest" && !party.guests.include?(current_user) 
      render :partial => "rsvp_form", locals: {party: party}
    end
  end

  def remove_rsvp(party, rsvp)
    if party.guests.include?(current_user)
      render partial: "rsvp_delete", locals: {rsvp: rsvp}
    end
  end
end

app/views/parties/_form.html.erb
<%= render partial: "layouts/errors", locals: {record: party} %>

<div class="form">
<%= form_for(party) do |f| %>
  
  <%= f.label :name %><br>
  <%= f.text_field :name %><br><br>
  
  <div class= "create_theme">
  <%= f.fields_for :theme do |theme| %>

    <%= theme.label :theme %> <br> 
    <%= theme.text_field :name %><br><br>

    <%= theme.label :era %> <br>
    <%= theme.text_field :era %><br><br>
  <% end %> 
  </div>
  <%= f.label :capacity %><br>
  <%= f.text_field :capacity %><br><br>

  <%= f.label :about %><br>
  <%= f.text_area :about %><br>

  <%= f.submit %>
<% end %> 
</div>

app/views/parties/_guestlist.html.erb
<ul class = "guest_list">
<% if !@party.guests.blank? %>
<h3>The Guest List</h3>
  <% @party.guests.each do |guest|%>
    <li><%=guest.name %></li>
  <% end %>
  <% else %>
    <h3> There is currently nobody attending. </h3>
<% end %>
</ul>

app/views/parties/_party_comments.html.erb
<div class= "party_comments">
<ul class= "list_of_comments">  
<% party.comments.each do |comment| %>
  <p><li><%= link_to comment.user.name, user_path(comment.user) %><%=  %>: 
  <%= comment.content %> <br>
  <%= link_to "View full comment", party_comment_path(party, comment) %>
  <% if current_user == comment.user %>
    <%= link_to "Edit your post", edit_party_comment_path(party, comment) %></p></li> 
  <% end %>
<% end %></ul>
<div class= "new comments">
<%= form_for Comment.new do |f| %>
  <%= f.label "Write your comment here:" %><br>
  <%= f.text_area :content %>
  <%= f.hidden_field :party_id, value: party.id %><br>
  <%= f.submit %>
<% end %>
</div>
</div>

app/views/parties/_rsvp_delete.html.erb
<h3> I can’t make it anymore </h3>
<%= button_to "Remove myself from the list", rsvp_path(rsvp), method: :delete %>

app/views/parties/_rsvp_form.html.erb
<%= form_for Rsvp.new do |f| %>
  <%= f.hidden_field :party_id, value: party.id %>
  <%= f.submit " RSVP" %>
<% end %>

app/views/parties/edit.html.erb
<%= render partial: "form", locals: {party: @party} %>
<br>
<div class ="delete_button">
  <%= button_to "Delete party", party_path(@party), method: :delete, data: { confirm: "Are you sure you want to delete this event?" } %>
</div>

app/views/parties/index.html.erb
<%= render partial: "layouts/flash_errors" %>
<h3>Here is a list of all the parties</h3>
<ul>
<% @parties.each do |party| %>
   <li> <%= link_to party.name, party_path(party) %> </li>
<% end %>
</ul>

<div class="scope_search">
<%= form_tag parties_path, method: :get do %>
  <%= label_tag :search %>
  <%= text_field_tag :search, @params[:search]%>
  <%= submit_tag "Search" %>
<% end %><br>

<%= form_tag parties_path, method: :get do %>
  <%= select_tag :sort, raw("
  <option value='popular_parties'>Most popular</option>
  <option value='newest_party'>Recently added</option>
  <option value='oldest_party'>Older parties</option>
  ") %>
  <%= submit_tag "Re-Order" %>
<% end %>
</div>

app/views/parties/new.html.erb
<h2>Create a new party</h2>
<%= render partial: "form", locals: {party: @party} %>

app/views/parties/show.html.erb
<h2> Party name: <%= @party.name %> <br> </h2>
<h3> Theme of the party: <%= @party.theme.name %> <br>
Party capacity: <%= @party.capacity %> <br></h3>
<h4>About this party:</h4> 
<p class = "about"> <%= @party.about %>  </p>
This party is brought to you by <strong><%= @party.host.name %></strong></div><br>

<%= render partial: "guestlist", locals: {party: @party} %>

<div class= "rsvp-field">
  <%= rsvp_button(@party)%>
  <%= remove_rsvp(@party, @rsvp)%>
</div>
<% if current_user == @party.host %>
  Click <%= link_to "here", edit_party_path(@party) %> to edit party details.
<%end%>
<p><%= render partial: "party_comments", locals: {party: @party} %></p>

<p> Click <%= link_to "here", new_party_comment_path(@party) %> to create a new comment.</p>