config/routes.rb
Rails.application.routes.draw do
  
  # resources :themes
  resources :parties do
    resources :comments, only: [:show, :edit, :update, :destroy, :new]
  end

  
  resources :comments, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :users, only: [:new, :create, :destroy, :update, :show]
  resources :rsvps, only: [:new, :create, :destroy]
  resources :hosts, :controller => 'users', type: "Host"
  resources :guests, :controller => 'users', type: "Guest"
  
  get '/home' => 'users#index'
  get '/users' => 'users#new'
  get '/user/edit' => 'users#edit'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  #need to delete this logout get path later on
  post '/logout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#facebook_omniauth'
  get '/auth/google_oauth2/callback' => 'sessions#google_omniauth' 

  root "sessions#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates_presence_of :content
  validates_presence_of :party_id
  belongs_to :user
  belongs_to :party
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login


  def new
    @comment = Comment.new
    @party = Party.find(params[:party_id])
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def create
    @comment = Comment.new(comment_params)
    current_user.comments << @comment
    @comment.save
    @party = Party.find(params[:comment][:party_id])
    redirect_to party_path(@party)
  end

  def edit
    @comment = Comment.find(params[:id])
    @party = Party.find(params[:party_id])
    redirect_back(fallback_location: root_path) unless current_user == @comment.user
    # return head(:forbidden) unless current_user == @comment.user
    #deciding on which is better.
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    if @comment.save
      redirect_to party_path(@comment.party)
    else
      render :edit
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    party = comment.party
    comment.destroy
    redirect_to party_path(party)
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :party_id)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<-- removed the error render from this form -->

<div class="form">
<%= form_for(comment) do |f| %>
  
    <%= f.label :content %><br>
    <%= f.text_area :content %><br>
    <%= f.hidden_field :party_id, value: party.id %><br>
    <%= f.submit %>
  <% end %> 
</div>

app/views/comments/edit.html.erb
<%= render partial: "form", locals: {comment: @comment, party: @party} %>
<br>
<div class ="delete_button">
  <%= button_to "Delete comment", comment_path(@comment), method: :delete, data: { confirm: "Are you sure you want to delete this comment?" } %>
</div>

app/views/comments/new.html.erb
<%= render partial: "form", locals: {comment: @comment, party: @party} %>

app/views/comments/show.html.erb
<h2><%=  @comment.user.name %></h2>
<h3><%=  @comment.content %></h3>

<%= link_to "Back", :back %>