config/routes.rb
Rails.application.routes.draw do
  
  # resources :themes
  resources :parties do
    resources :comments, only: [:show, :edit, :update, :destroy, :new]
  end

  
  resources :comments, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :users, only: [:new, :create, :destroy, :update, :show]
  resources :rsvps, only: [:new, :create, :destroy]
  resources :hosts, :controller => 'users', type: "Host"
  resources :guests, :controller => 'users', type: "Guest"
  
  get '/home' => 'users#index'
  get '/users' => 'users#new'
  get '/user/edit' => 'users#edit'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  #need to delete this logout get path later on
  post '/logout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#facebook_omniauth'
  get '/auth/google_oauth2/callback' => 'sessions#google_omniauth' 

  root "sessions#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP } 
  validates :password, length: {minimum: 8, allow_nil: true}
  
  has_many :rsvps, dependent: :destroy
  has_many :comments, dependent: :destroy

  def self.o_auth_find_info(user_info)
    user= find_or_create_by(email: user_info['email']) do |u|
      u.name = user_info['name']
      u.image = user_info['image']
      u.password = SecureRandom.hex
    end 
  end    

  def host_or_guest_account
    self.!params[:user][:admin].empty? ? Host.create(user_params) : Guest.create(user_params)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login
  skip_before_action :require_login, only: [:new, :create, :index]

  def index 
    if !logged_in?
      redirect_to '/users/new'
    end
    @user = current_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)  
    if @user.valid?
      @user = params[:user][:admin]== "1" ? Host.create(user_params) : Guest.create(user_params)
      session[:user_id] = @user.id
      redirect_to "/home"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user= current_user

  end

  def update
    @user= current_user
    @user.update(user_params_for_update)
    if @user.save
      redirect_to home_path
    else
      render :edit
    end
  end

  def destroy
    @user= current_user
    if @user.authenticate(params[:user][:password])
      @user.destroy
      session.clear 
      redirect_to "/"
    else
      flash[:alert] = "Invalid password."
      redirect_to "/user/edit"
    end
  end

  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

  def user_params_for_update
    params.require(params[:type].to_sym.downcase).permit(:name)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= render partial: "layouts/errors", locals: {record: user} %>
<div class="form">
<%= form_for(user) do |f| %>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
  
    <%= f.label :email %><br>
    <%= f.text_field :email %><br>

    <%= f.label "Are you a party host?" %><br>
    <%= f.check_box :admin %><br>

    <%= f.label :password %><br>
    <%= f.password_field :password %><br>

    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %><br>

    <%= f.submit %>
  <% end %> 
  </div><br>

  <p>You can also create an account with  <%= link_to('Facebook', '/auth/facebook')%> or
  <%= link_to('Google', '/auth/google_oauth2')%>. <br>
  Please note, you will not have access to create parties with this type of profile.</p>

app/views/users/_party_list.html.erb
<% if !@user.parties.empty? %>
<ul class= "list">
<% @user.parties.each do |party| %>
     <li> <%= link_to party.name, party_path(party) %> </li>
    <% end %>
</ul>
<% else %>
  There are currently no parties in the horizon.
<% end %>

app/views/users/_update_user_info_form.html.erb
<%= render partial: "layouts/errors", locals: {record: user} %>
<div class="form">
<%= form_for(user)do |f| %>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>

    <%= f.submit "Update" %>
  <% end %> 
  </div>

app/views/users/edit.html.erb
<%= render partial: "update_user_info_form", locals: {user: @user} %>

<br><br>
<div class = "delete field">
  <% flash.each do |type, msg| %>
    <div class="errors">
      <%= msg %>
    </div>
  <% end %>
  <%= form_tag user_path(@user), method: "delete" do %>
    <%= label_tag "Please enter your password."  %> <br>
    <%= password_field_tag 'user[password]' %><br>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <input value='Delete Account' type='submit' id='submit-form'/>
  <% end %>
</div>

app/views/users/index.html.erb
<h1> Welcome <%= @user.name %> </h1>


<p class="party_list">Here's a list of your parties
<%= render partial: "party_list", locals: {user: @user} %>
<br><br>
<% if current_user.type == "Host" %>
  <%= link_to "Create a new party", new_party_path %>
<% end %></p>

<p class= "edit">Click here to <%= link_to "edit", "/user/edit" %> your details.</p>

app/views/users/new.html.erb
<%= render partial: "form", locals: {user: @user} %>

app/views/users/show.html.erb
<h1> This is <%= @user.name %> </h1>

<p><% if @user.type== "Host" %>
  Here are the list of parties <%= @user.name %> is hosting 
<% else %>
  Here are the list of parties  <%= @user.name %> is attending:
<% end %>
<%= render partial: "party_list", locals: {user: @user} %></p>