config/routes.rb
Rails.application.routes.draw do
  
  # resources :themes
  resources :parties do
    resources :comments, only: [:show, :edit, :update, :destroy, :new]
  end

  
  resources :comments, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :users, only: [:new, :create, :destroy, :update, :show]
  resources :rsvps, only: [:new, :create, :destroy]
  resources :hosts, :controller => 'users', type: "Host"
  resources :guests, :controller => 'users', type: "Guest"
  
  get '/home' => 'users#index'
  get '/users' => 'users#new'
  get '/user/edit' => 'users#edit'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  #need to delete this logout get path later on
  post '/logout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#facebook_omniauth'
  get '/auth/google_oauth2/callback' => 'sessions#google_omniauth' 

  root "sessions#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if record.errors.any? %>
  <ul class="errors">
    <% record.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_flash_errors.html.erb
<% flash.each do |type, msg| %>
<div class="alert alert-info">
  <%= msg %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar">

 <%= image_tag "", class: "site-logo"%>
    <ul class= nav> 
      <li><%= link_to "Home Page", "/" %></li>
      <li><%= link_to "List of Parties", parties_path %></li>
      <li><%=link_to "Logout", logout_path %></li>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Party Advisor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div id= "body_of_site">
    <%= yield %>
    </div>
  </body>
</html>